# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('golfer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('golfer_name', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Golfer',
            },
        ),
        migrations.CreateModel(
            name='GolferRoundScores',
            fields=[
                ('grs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grs_total_score', models.IntegerField()),
                ('grs_hole1_score', models.IntegerField()),
                ('grs_hole2_score', models.IntegerField()),
                ('grs_hole3_score', models.IntegerField()),
                ('grs_hole4_score', models.IntegerField()),
                ('grs_hole5_score', models.IntegerField()),
                ('grs_hole6_score', models.IntegerField()),
                ('grs_hole7_score', models.IntegerField()),
                ('grs_hole8_score', models.IntegerField()),
                ('grs_hole9_score', models.IntegerField()),
                ('grs_hole10_score', models.IntegerField()),
                ('grs_hole11_score', models.IntegerField()),
                ('grs_hole12_score', models.IntegerField()),
                ('grs_hole13_score', models.IntegerField()),
                ('grs_hole14_score', models.IntegerField()),
                ('grs_hole15_score', models.IntegerField()),
                ('grs_hole16_score', models.IntegerField()),
                ('grs_hole17_score', models.IntegerField()),
                ('grs_hole18_score', models.IntegerField()),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Golfers Round Scores',
                'verbose_name': 'Golfer Round Scores',
                'db_table': 'GolferRoundScores',
            },
        ),
        migrations.CreateModel(
            name='GolferTournScores',
            fields=[
                ('gts_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gts_total_score', models.IntegerField()),
                ('gts_round1_score', models.IntegerField()),
                ('gts_round2_score', models.IntegerField()),
                ('gts_round3_score', models.IntegerField()),
                ('gts_round4_score', models.IntegerField()),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Golfers Tournament Scores',
                'verbose_name': 'Golfer Tournament Scores',
                'db_table': 'GolferTournScores',
            },
        ),
        migrations.CreateModel(
            name='TournGolfer',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Tournament Golfers',
                'verbose_name': 'Tournament Golfer',
                'db_table': 'TournGolfer',
            },
        ),
    ]
