# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.IntegerField(primary_key=True, serialize=False)),
                ('round_day', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Round',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tourn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tourn_name', models.TextField()),
                ('tourn_start_date', models.TextField()),
                ('tourn_num_rounds', models.IntegerField()),
                ('tourn_num_golfers', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Tournament',
            },
        ),
        migrations.CreateModel(
            name='TournScores',
            fields=[
                ('ts_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ts_top_score', models.IntegerField()),
                ('ts_top_round1_score', models.IntegerField()),
                ('ts_top_round2_score', models.IntegerField()),
                ('ts_top_round3_score', models.IntegerField()),
                ('ts_top_round4_score', models.IntegerField()),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Tournament Scores',
                'verbose_name': 'Tournament Scores',
                'db_table': 'TournScores',
            },
        ),
    ]
